name: release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - {os: 'linux', arch: 'amd64', exp: ''}
          - {os: 'linux', arch: 'arm64', exp: ''}
          - {os: 'darwin', arch: 'amd64', exp: ''}
          - {os: 'darwin', arch: 'arm64', exp: ''}
          - {os: 'windows', arch: 'amd64', exp: '.exe'}
          - {os: 'windows', arch: 'arm64', exp: '.exe'}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOOS=${{matrix.job.os}} GOARCH=${{matrix.job.arch}} go build -o dist/devtool-${{matrix.job.os}}-${{matrix.job.arch}}${{matrix.job.exp}} -ldflags="-s -w"
      - name: upload
        uses: actions/upload-artifact@master
        with:
          name: devtool-${{matrix.job.os}}-${{matrix.job.arch}}${{matrix.job.exp}}
          path: dist/devtool-${{matrix.job.os}}-${{matrix.job.arch}}${{matrix.job.exp}}
      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: mkdir dist
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
          patter: devtool-*
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: ls -R dist
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          body: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "dist/*"