name: release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - {os: 'linux', arch: 'amd64', exp: ''}
          - {os: 'linux', arch: 'arm64', exp: ''}
          - {os: 'darwin', arch: 'amd64', exp: ''}
          - {os: 'darwin', arch: 'arm64', exp: ''}
          - {os: 'windows', arch: 'amd64', exp: '.exe'}
          - {os: 'windows', arch: 'arm64', exp: '.exe'}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOOS=${{matrix.job.os}} GOARCH=${{matrix.job.arch}} go build -o dist/devtool-${{matrix.job.os}}-${{matrix.job.arch}}${{matrix.job.exp}} -ldflags="-s -w"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/devtool-${{matrix.job.os}}-${{matrix.job.arch}}${{matrix.job.exp}}